### ISSUE TITLE
Flesh out welcome message

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-education/uctech-greeter#1]
Replace dummy text in `welcome.txt` with actual contents.
https://github.com/stopfstedt/uctech-greeter/blob/master/welcome.txt

These [basic formatting options](https://api.slack.com/docs/message-formatting) can be applied.

**Comment by tmarconi** [comment]
Hmm, my pull request doesn't have formatting, it would be good to see how it looks as is :)

**Comment by stopfstedt** [comment]
thanks @tmarconi - will deploy the code to sandbox later and send you an invite.
will need to augment greeterbot to respond with the welcome message on demand, not just on joining the team.

**Comment by stopfstedt** [comment]
refs #7
