### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-education/uctech-greeter#18]
it's been a while, do it.

```
$ npm outdated
Package        Current  Wanted  Latest  Location
app-root-path    2.2.1   2.2.1   3.0.0  uctech-greeter
botkit           0.5.8   0.5.8   4.6.2  uctech-greeter
dotenv           4.0.0   4.0.0   8.2.0  uctech-greeter
eslint          4.19.1  4.19.1   6.8.0  uctech-greeter

```

**Comment by Trott** [comment]
botkit to 4.6.2 is a significant change but botkit to 0.7.4 still silences a lot of `npm audit` warnings (not all of them) and also supplies a helpful warning message at startup that we'll have to address before updating to 4.x.x. So, as an incremental step in the right direction: https://github.com/ucsf-ckm/uctech-greeter/pull/21

I also enabled dependabot for this repo.

**Comment by stopfstedt** [comment]
superseded  by #21
